# -*- coding: utf-8 -*-
"""Copy of YOLOv8CustomObjectDetection.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DW3PqnxMUOpqdQyNAPR6BSgebGmcsRjS

## How to Train YOLOv8 Object Detection on a Custom Dataset
"""

!nvidia-smi

!pip install ultralytics

"""## Install YOLOv8"""

from ultralytics import YOLO
import os
from IPython.display import display, Image
from IPython import display
display.clear_output()
!yolo mode=checks

"""## Inference Example with Pretrained YOLOv8 Model"""

!yolo task=detect mode=predict model=yolov8n.pt conf=0.25 source='https://media.roboflow.com/notebooks/examples/dog.jpeg'

Image(filename='runs/detect/predict/dog.jpeg', height=600)

"""## Train YOLOv8 Model on Custom Dataset"""

!pip install roboflow

from roboflow import Roboflow
rf = Roboflow(api_key="zOVRuKL1Cgn8StLIkap2")
project = rf.workspace("mohamed-ahmed-sydwr").project("dental-tools-hhfgb")
dataset = project.version(1).download("yolov8")

!yolo task=detect mode=train model=yolov8m.pt data={dataset.location}/data.yaml epochs=50 imgsz=640

Image(filename=f'/content/runs/detect/train2/confusion_matrix.png', width=600)

Image(filename=f'/content/runs/detect/train2/results.png', width=600)

!yolo task=detect mode=val model=/content/runs/detect/train2/weights/best.pt data={dataset.location}/data.yaml

!yolo task=detect predict model=/content/runs/detect/train2/weights/best.pt conf=0.25 source={dataset.location}/test/images

pip install supervision